---
title: "component"
format: html
editor: visual
---
<!-- installing libraries -->

```{r, message=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(maps)
library(plotly )
library(tidyverse)
library(vdemdata)
library(ggplot2)
library(gganimate)
```

<!-- loading dataset -->

```{r, message=FALSE}
vdemfull <- vdemdata::vdem
onlycountries <- vdemfull[-c(25990:27555), ]

map <- map_data("world")
map$region[map$region == "USA"] = "United States of America"
map$region[map$region == "UK"] = "United Kingdom"
map$region[map$region == "Czech Republic"] = "Czechia"
```

<!-- womens empowerment variables -->

```{r}
allwemp <- onlycountries %>% select(region = country_name, abbr = country_text_id, id = country_id, year = year, wpei = v2x_gender, liberties = v2x_gencl, society = v2x_gencs, participation = v2x_genpp)
wemp100yr <- filter(allwemp, year >= 1900, year <= 2000)
mapwemp100yr <- left_join(wemp100yr, map, by = "region")
```

<!-- voting rights -->

```{r}
allvoting <- onlycountries %>% select(region = country_name, abbr = country_text_id, id = country_id, year = year, voting = v2fsuffrage)
voting100yr <- filter(allvoting, year >1899, year <2001)
mapvoting100yr <- left_join(voting100yr, map, by = "region")
```

<!-- suffrage maps -->

```{r, message=FALSE, warning=FALSE}
vote1900 <- filter(mapvoting100yr, year == 1900)
actualvote1900<-filter(vote1900, voting > 0)
vote1925 <- filter(mapvoting100yr, year == 1925)
actualvote1925<-filter(vote1925, voting > 0)
vote1950 <- filter(mapvoting100yr, year == 1950)
actualvote1950<-filter(vote1950, voting > 0)
vote1975 <- filter(mapvoting100yr, year == 1975)
actualvote1975<-filter(vote1975, voting > 0)
vote2000 <- filter(mapvoting100yr, year == 2000)
actualvote2000<-filter(vote2000, voting > 0)
#basemap
basemap <- ggplot() + geom_map(data = map, map = map, aes(long, lat, map_id = region))
#1900 map
basemap + geom_map(data = actualvote1900, map = vote1900, aes(long, lat, map_id = region), fill="purple")
#1925 map
basemap + geom_map(data = actualvote1925, map = vote1925, aes(long, lat, map_id = region), fill="purple")
#1950 map
basemap + geom_map(data = actualvote1950, map = vote1950, aes(long, lat, map_id = region), fill = "purple")
#1975 map
basemap + geom_map(data = actualvote1975, map = vote1975, aes(long, lat, map_id = region), fill="purple")
#2000 map
basemap + geom_map(data = actualvote2000, map = vote2000, aes(long, lat, map_id = region), fill = "purple")
```


<!-- wpei maps -->

```{r message=False, warning=FALSE}
wemp1900 <- filter(mapwemp100yr, year == 1900)
wemp1925 <- filter(mapwemp100yr, year == 1925)
wemp1950 <- filter(mapwemp100yr, year == 1950)
wemp1975 <- filter(mapwemp100yr, year == 1975)
wemp2000 <- filter(mapwemp100yr, year == 2000)
#basemap
basemap <- ggplot() + geom_map(data = map, map = map, aes(long, lat, map_id = region)) + scale_fill_gradient(low = "yellow", high = "pink")
#1900 map
basemap + geom_map(data = wemp1900, map = wemp1900, aes(fill = wpei, map_id = region))
#1925 map
basemap + geom_map(data = wemp1925, map = wemp1925, aes(fill = wpei, map_id = region))
#1950 map
basemap + geom_map(data = wemp1950, map = wemp1950, aes(fill = wpei, map_id = region))
#1975 map
basemap + geom_map(data = wemp1975, map = wemp1975, aes(fill = wpei, map_id = region))
#2000 map
basemap + geom_map(data = wemp2000, map = wemp2000, aes(fill = wpei, map_id = region))
```