---
title: "data_cleaning"
format: html
editor: visual
---

<!-- installing libraries -->

```{r, message=FALSE}
library(readr)
library(dplyr)
library(tidyr)
library(maps)
library(tidyverse)
library(vdemdata)
library(ggplot2)
```

<!-- dataset -->

```{r, message=FALSE}
vdemfull <- vdemdata::vdem
#vdemfull$year <- as.factor(vdemfull$year)
map <- map_data("world")
map$region[map$region == "USA"] = "United States of America"
map$region[map$region == "UK"] = "United Kingdom"
onlycountries <- vdemfull[-c(25990:27555), ]
```

<!-- womens empowerment variables -->

```{r}
allwemp <- onlycountries %>% select(region = country_name, abbr = country_text_id, id = country_id, year = year, wpei = v2x_gender, liberties = v2x_gencl, society = v2x_gencs, participation = v2x_genpp)
wemp100yr <- filter(allwemp, year >= 1900, year <= 2001)
mapwemp <- left_join(wemp100yr, map, by = "region")
```

<!-- voting rights -->

```{r}
allvoting <- onlycountries %>% select(region = country_name, abbr = country_text_id, id = country_id, year = year, voting = v2fsuffrage)
voting100yr <- filter(allvoting, year >1899, year <2001)
#voting100yr <- voting100yr %>% mutate(voting = ifelse(is.na(voting), 0, voting))
mapvoting100yr <- left_join(voting100yr, map, by = "region")
vote1900 <- filter(mapvoting100yr, year == 1900)
actualvote1900<-filter(vote1900, voting > 0)
vote1950 <- filter(mapvoting100yr, year == 1950)
actualvote1950<-filter(vote1950, voting > 0)
vote2000 <- filter(mapvoting100yr, year == 2000)
actualvote2000<-filter(vote2000, voting > 0)
```

<!-- creating a csv file of cleaned data -->

```{r}
#write.csv(wemp100yr, 'wemp100yr.csv')
#write.csv(voting100yr, 'voting100yr.csv')
```

<!-- suffrage map -->

```{r, message=FALSE, warning=FALSE}
#basemap
basemap <- ggplot() + geom_map(data = map, map = map, aes(long, lat, map_id = region))
#1900 map
basemap + geom_map(data = actualvote1900, map = vote1900, aes(long, lat, map_id = region), fill="purple")
#1950 map
basemap + geom_map(data = actualvote1950, map = vote1950, aes(long, lat, map_id = region), fill = "purple")
#2000 map
basemap + geom_map(data = actualvote2000, map = vote2000, aes(long, lat, map_id = region), fill = "purple")
```
